"""
gap-report.py — Phase 7: Analyze the full dataset and produce a gap report.
Checks: alias integrity, course lookup gaps, credit sums, coverage matrix.
"""

import yaml, os, glob, sys

CATALOG = 'data/catalog-years.yaml'
DEGREES_DIR = 'data/degrees'
COURSES_DIR = 'data/courses'
GEN_ED_DIR = 'data/gen-ed'

def load_yaml(path):
    with open(path, 'r', encoding='utf-8') as f:
        return yaml.safe_load(f)

# Load catalog
catalog = load_yaml(CATALOG)

# Load all courses files
courses_by_file = {}
for cf in glob.glob(os.path.join(COURSES_DIR, 'courses-*.yaml')):
    basename = os.path.basename(cf)
    raw_data = load_yaml(cf)
    # Courses files may have a 'courses:' wrapper or be flat dicts
    if raw_data and 'courses' in raw_data and isinstance(raw_data['courses'], dict):
        courses_by_file[basename] = set(raw_data['courses'].keys())
    elif raw_data and isinstance(raw_data, dict):
        courses_by_file[basename] = set(raw_data.keys())
    else:
        courses_by_file[basename] = set()

# Load gen-ed templates
gen_ed_templates = {}
for gf in glob.glob(os.path.join(GEN_ED_DIR, '*.yaml')):
    basename = os.path.basename(gf).replace('.yaml', '')
    gen_ed_templates[basename] = load_yaml(gf)

# Collect all degree files that exist on disk
existing_degree_files = set()
for root, dirs, files in os.walk(DEGREES_DIR):
    for f in files:
        if f.endswith('.yaml'):
            rel = os.path.relpath(os.path.join(root, f), 'data').replace('\\', '/')
            existing_degree_files.add(rel)

# ---- Analysis ----

report_lines = []
def out(s=''):
    report_lines.append(s)

out('# Phase 7 — Gap Report')
out('Generated by gap-report.py')
out()

# 1. Coverage Matrix
out('## 1. Coverage Matrix')
out()
out('| Year | Degrees | Canonical (file:) | Aliases | courses_file |')
out('|------|---------|-------------------|---------|-------------|')
for y in catalog['years']:
    yid = y['id']
    total = len(y['degrees'])
    canonical = sum(1 for d in y['degrees'] if 'file' in d)
    aliases = sum(1 for d in y['degrees'] if 'alias_of' in d)
    cf = y.get('courses_file', '???')
    out(f'| {yid} | {total} | {canonical} | {aliases} | {cf} |')
out()

# 2. Broken Aliases — alias_of points to a year/id where no file exists
out('## 2. Broken Aliases')
out()

# Build map of canonical degree files: year_id/degree_id -> file path
canonical_map = {}
for y in catalog['years']:
    for d in y['degrees']:
        if 'file' in d:
            canonical_map[f"{y['id']}/{d['id']}"] = d['file']

broken_aliases = []
for y in catalog['years']:
    for d in y['degrees']:
        if 'alias_of' in d:
            target = d['alias_of']
            # Check if target exists as a canonical entry
            if target not in canonical_map:
                broken_aliases.append((y['id'], d['id'], target))

if broken_aliases:
    out(f'**{len(broken_aliases)} broken aliases found:**')
    out()
    out('| Year | Degree | Points to | Issue |')
    out('|------|--------|-----------|-------|')
    for yr, did, target in broken_aliases:
        out(f'| {yr} | {did} | {target} | Target not found as canonical entry |')
else:
    out('No broken aliases found.')
out()

# 3. Degree files on disk not referenced in catalog-years.yaml
out('## 3. Orphan Degree Files')
out()
referenced_files = set()
for y in catalog['years']:
    for d in y['degrees']:
        if 'file' in d:
            referenced_files.add(d['file'])

orphans = existing_degree_files - referenced_files
if orphans:
    out(f'**{len(orphans)} degree files on disk not referenced in catalog-years.yaml:**')
    out()
    for o in sorted(orphans):
        out(f'- `{o}`')
else:
    out('All degree files are referenced.')
out()

# 4. Course Lookup Gaps — courses in degree YAMLs not in the courses file
out('## 4. Course Lookup Gaps')
out()

def extract_courses_from_degree(deg_data):
    """Extract all course codes referenced in a degree YAML."""
    codes = set()
    for cat in deg_data.get('categories', []):
        for c in cat.get('courses', []):
            codes.add(c)
        for opt in cat.get('options', []):
            codes.add(opt)
        # choose_track
        ct = cat.get('choose_track', {})
        if isinstance(ct, dict):
            for track_courses in ct.values():
                if isinstance(track_courses, list):
                    for c in track_courses:
                        codes.add(c)
        # tracks (alternate format)
        for t in cat.get('tracks', []):
            if isinstance(t, dict):
                for c in t.get('courses', []):
                    codes.add(c)
    return codes

def extract_gen_ed_courses(template_name):
    """Extract default course codes from a gen-ed template."""
    tmpl = gen_ed_templates.get(template_name, {})
    codes = set()
    for cat in tmpl.get('categories', []):
        d = cat.get('default')
        if d:
            codes.add(d)
        for sub in cat.get('subcategories', []):
            sd = sub.get('default')
            if sd:
                codes.add(sd)
    return codes

course_gaps = []
for y in catalog['years']:
    courses_file = y.get('courses_file', '')
    courses_basename = os.path.basename(courses_file)
    available = courses_by_file.get(courses_basename, set())

    for d in y['degrees']:
        if 'file' not in d:
            continue  # skip aliases — they'll be checked under their canonical year

        deg_path = os.path.join('data', d['file'])
        if not os.path.exists(deg_path):
            continue

        deg_data = load_yaml(deg_path)
        if not deg_data:
            continue

        deg_courses = extract_courses_from_degree(deg_data)

        # Also get gen-ed defaults
        ge = deg_data.get('gen_ed', {})
        template_name = ge.get('template', '')
        ge_courses = extract_gen_ed_courses(template_name)

        all_courses = deg_courses | ge_courses
        missing = all_courses - available

        if missing:
            course_gaps.append((y['id'], d['id'], sorted(missing)))

if course_gaps:
    out(f'**{len(course_gaps)} degrees with courses not in their year\'s courses file:**')
    out()
    for yr, did, missing in course_gaps:
        out(f'- **{yr}/{did}**: {", ".join(missing)}')
else:
    out('All degree course codes found in their respective courses files.')
out()

# 5. Term Pins Status
out('## 5. Term Pins Status')
out()
has_pins = []
no_pins = []
for y in catalog['years']:
    for d in y['degrees']:
        if 'file' not in d:
            continue
        deg_path = os.path.join('data', d['file'])
        if not os.path.exists(deg_path):
            continue
        deg_data = load_yaml(deg_path)
        if not deg_data:
            continue
        if deg_data.get('term_pins'):
            has_pins.append(f"{y['id']}/{d['id']}")
        else:
            no_pins.append(f"{y['id']}/{d['id']}")

out(f'- Degrees with term_pins: **{len(has_pins)}**')
out(f'- Degrees without term_pins: **{len(no_pins)}**')
if has_pins:
    out(f'- With pins: {", ".join(has_pins[:10])}{"..." if len(has_pins) > 10 else ""}')
out()

# 6. Flagged Degrees (from Phase 5)
out('## 6. Known Issues from Prior Phases')
out()
flagged = [
    ('2025-26', 'social-sciences-ba', 'Scraper only captured 7 courses; needs re-extraction'),
    ('2025-26', 'nursing-rn-to-bsn', 'RN completion program structure differs from standard'),
    ('2025-26', 'physical-education-k12-ba', 'Page has multiple concentration sections mixed together'),
    ('2022-25', 'fine-arts-bfa', 'Teaching Art track (142 cr) not modeled in 2022-25; aliases to 2020-21 standard tracks (120 cr)'),
]
out('| Year | Degree | Issue |')
out('|------|--------|-------|')
for yr, did, issue in flagged:
    out(f'| {yr} | {did} | {issue} |')
out()

# 7. Credit Verification Spot Check
out('## 7. Credit Verification (canonical degrees only)')
out()
credit_issues = []
for y in catalog['years']:
    for d in y['degrees']:
        if 'file' not in d:
            continue
        deg_path = os.path.join('data', d['file'])
        if not os.path.exists(deg_path):
            continue
        deg_data = load_yaml(deg_path)
        if not deg_data:
            continue

        total = deg_data.get('total_credits', 0)
        ge = deg_data.get('gen_ed', {})
        template_name = ge.get('template', '')

        # Gen-ed credits: start from template, apply overrides
        tmpl = gen_ed_templates.get(template_name, {})
        tmpl_credits = {cat['id']: cat.get('credits', 0) for cat in tmpl.get('categories', [])}
        ge_credits = sum(tmpl_credits.values())

        for ov in ge.get('overrides', []):
            if not isinstance(ov, dict):
                continue
            cat_id = ov.get('category', '')
            if ov.get('_remove'):
                ge_credits -= tmpl_credits.get(cat_id, 0)
            elif 'credits' in ov and cat_id in tmpl_credits:
                ge_credits += ov['credits'] - tmpl_credits[cat_id]

        # Sum category credits
        cat_credits = sum(c.get('credits', 0) for c in deg_data.get('categories', []))

        computed = ge_credits + cat_credits
        if computed != total and abs(computed - total) > 3:
            credit_issues.append((y['id'], d['id'], total, computed, ge_credits, cat_credits))

if credit_issues:
    out(f'**{len(credit_issues)} degrees with credit discrepancy > 3:**')
    out()
    out('| Year | Degree | Stated | Computed | Gen-Ed | Categories | Delta |')
    out('|------|--------|--------|----------|--------|------------|-------|')
    for yr, did, stated, computed, ge, cat in credit_issues:
        delta = computed - stated
        out(f'| {yr} | {did} | {stated} | {computed} | {ge} | {cat} | {delta:+d} |')
else:
    out('All degrees within 3 credits of stated total.')
out()

# 8. Summary Stats
out('## 8. Summary')
out()
total_canonical = sum(1 for y in catalog['years'] for d in y['degrees'] if 'file' in d)
total_aliases = sum(1 for y in catalog['years'] for d in y['degrees'] if 'alias_of' in d)
total_degree_files = len(existing_degree_files)
out(f'- Total catalog entries: {sum(len(y["degrees"]) for y in catalog["years"])}')
out(f'- Canonical entries (file:): {total_canonical}')
out(f'- Alias entries: {total_aliases}')
out(f'- Degree YAML files on disk: {total_degree_files}')
out(f'- Course files: {len(courses_by_file)} ({", ".join(sorted(courses_by_file.keys()))})')
out(f'- Courses in 2020-21: {len(courses_by_file.get("courses-2020-21.yaml", set()))}')
out(f'- Courses in 2025-26: {len(courses_by_file.get("courses-2025-26.yaml", set()))}')

# Write report
report = '\n'.join(report_lines)
print(report)

with open('data/extraction-notes/gap-report.md', 'w', encoding='utf-8') as f:
    f.write(report)
print('\n--- Written to data/extraction-notes/gap-report.md ---')
